alias setJdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
alias setJdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
alias setJdk9='export JAVA_HOME=$(/usr/libexec/java_home -v 1.9)'
alias setJdk11='export JAVA_HOME=$(/usr/libexec/java_home -v 11)'
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=/usr/local/sbin:/usr/local/bin/:$PATH
export GOPATH=/Users/damonx/Development/golangpath
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/damonx/.sdkman"
[[ -s "/Users/damonx/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/damonx/.sdkman/bin/sdkman-init.sh"
